[package]
name = "crate_tutorial"
version = "0.1.0"
authors = ["Trent Daniel <trent.daniel65@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
